#!/bin/dash

if [ -d ".girt" ]
then
	echo "$0: error: .girt already exists"
	exit 1
else
	mkdir .girt
	mkdir -p .girt/index		# create index folder
	mkdir -p .girt/repository 	# create repository folder
	touch .girt/logs			# create logs file
	echo "Initialized empty girt repository in .girt"
	exit 0
fi

