#!/bin/dash

if [ -d ".girt" ]
then
	echo "$0: error: .girt already exists"
	exit 1
else
	mkdir .girt
	touch ./.girt/text.txt
	mkdir -p .girt/index	# create index folder
	echo "Initialized empty girt repository in .girt"
fi

