#!/bin/dash

# test .girt exists
if ! test -d .girt
then
	echo "$0: error: girt repository directory .girt not found"
	exit 1
fi

# check if first commit exists
if ! test -d ".girt/master/commit_0"
then
	echo "girt-branch: error: this command can not be run until after the first commit"
	exit 1
fi

# initialize variables
branch=$( cat .girt/branch )

# test input 
if test $# -eq 2 && test $1 = "-d"
then
	# cannot delete master
	if test $2 = "master"
	then
		echo "girt-branch: error: can not delete branch 'master'"
		exit 1
	fi
	# if branch does not exist
	if ! test -d ".girt/${2}"
	then
		echo "girt-branch: error: branch '${2}' doesn't exist"
		exit 1
	fi
	# otherwise delete specified branch folder
	rm -r ".girt/${2}"
	echo "Deleted branch '${2}'"
	exit 0
elif test $# -eq 1 && ! test $1 = "-d"
then
	# check if the branch already exists
	if test -d ".girt/$1"
	then
		echo "girt-branch: error: branch '${1}' already exists"
		exit 1
	fi
	# otherwise create new branch by initializing new branch directory
	mkdir -p .girt/${1}
	mkdir -p .girt/${1}/index			# create index folder
	mkdir -p .girt/${1}/repository 		# create repository folder
	touch .girt/${1}/logs				# create logs file
elif test $# = 0
then
	# list all branches
	for dir in .girt/*
	do
		if test -d $dir; then echo $( echo "$dir" | cut -d'/' -f2 ); fi
	done | sort
else
	echo "usage: girt-branch [-d] <branch>"
	exit 1
fi
