#!/bin/dash

path="$@"
if test $# -eq 0 
then
	echo "Please enter an argument."
elif  test $# -eq 1 && echo "$1" | grep -E '^.$' >/dev/null 
then
	path='*'		
fi
# echo $path
for file in $path
do
	# check filename
	if  echo "$file" | grep -E '^[a-zA-Z0-9]+((.|-|_)*[a-zA-Z0-9]*)*(.|-|_)*'  > /dev/null
	then
		# add file to index
		dest="./.girt/index/${file}"
		cp "$file" "$dest"
	fi
done
