#!/bin/dash

if [ -d ".girt" ]
then
	echo "$0: error: .girt already exists"
	exit 1
else
	mkdir .girt
	echo 'master' > .girt/branch	# create file to record branches
	mkdir -p .girt/master/index			# create index folder
	mkdir -p .girt/master/repository 		# create repository folder
	touch .girt/master/logs				# create logs file
	
	echo "Initialized empty girt repository in .girt"
	exit 0
fi

