#!/bin/dash

if ! test -d .girt
then
	echo "$0: error: girt repository directory .girt not found"
	exit 1
fi

# test input argument
if ! test $# = 1
then 
	echo "usage: girt-show <commit>:<filename>"
	exit 1
fi

expected_file=$( echo $1 | cut -d':' -f2 )
commit_no=$( echo $1 | cut -d':' -f1 )



# If commit is omitted, the contents of the file in the index should be printed.
if test ${#commit_no} -eq 0 # ommit commit
then
	# test if file has been added (is in index)
	if ! test -f ".girt/index/$expected_file"
	then
		echo "girt-show: error: '${expected_file}' not found in index"
		exit 1
	fi
	cat ".girt/index/${expected_file}"
	exit 0
else
	# check commit exists
	if ! test -d ".girt/commit_${commit_no}"
	then
		echo "girt-show: error: unknown commit '${commit_no}'"
		exit 1
	else
		# test file has been commit
		if ! test -f ".girt/commit_${commit_no}/${expected_file}"
		then
			echo "girt-show: error: '${expected_file}' not found in commit ${commit_no}"
			exit 1
		else
			cat ".girt/commit_${commit_no}/${expected_file}"
			exit 0
		fi
	fi
fi
