#!/bin/dash

# test .girt exists
if ! test -d .girt
then
	echo "$0: error: girt repository directory .girt not found"
	exit 1
fi
# get usage
if test $# -eq 0 
then
	echo "usage: girt-add <filenames>"
	exit 1
fi

# get branch
branch=$( cat .girt/branch )
# iterate all args
for file in "$@"
do
	# check filename
	if  echo "$file" | grep -E -v '^[a-zA-Z0-9]+((.|-|_)*[a-zA-Z0-9]*)*(.|-|_)*'  > /dev/null
	then
		# girt-add: error: invalid filename '.'
		echo "girt-add: error: invalid filename '${file}'"
		exit 1
	fi

	# if file is a folder, "girt-add: error: 'test' is not a regular file"
	if test -d "$file"
	then
		echo "girt-add: error: '${file}' is not a regular file"
		exit 1
	fi

	# file no exists in both working direcotry and index
	# "girt-add: error: cannot open 'filename'"
	index=".girt/${branch}/index/${file}"
	if ! test -f "$file" && ! test -f "$index"
	then
		echo "girt-add: error: can not open '${file}'"
		exit 1
	fi

	# file has been removed in working directory, but exists in index
	# remove the file in index as well
	if ! test -f "$file" && test -f "$index"
	then
		rm "$index"
		exit 0
	fi

	# add file to index
	cp "$file" "$index"
done